"""
Django settings for employee_management project.

Generated by 'django-admin startproject' using Django 4.2.20.
"""

from pathlib import Path
import os
import dj_database_url

# -----------------------------------
# Base Directory
# -----------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------
# Security
# -----------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-o5^8l=)fh)la8p#azru&7!r@@#&o=lr)c@&e1_16aly2*22(s4')

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    os.getenv('RENDER_EXTERNAL_HOSTNAME', '')  # ✅ Auto add Render hostname
]

# -----------------------------------
# Installed Apps
# -----------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'employee',
    'corsheaders',
]

# -----------------------------------
# Middleware
# -----------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',          # ✅ CORS on top
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',     # ✅ For static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'employee_management.urls'

# -----------------------------------
# Templates
# -----------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'employee_management.wsgi.application'

# -----------------------------------
# Database Configuration
# -----------------------------------
if os.getenv('DATABASE_URL'):
    # ✅ Render / Production
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
else:
    # ✅ Local MySQL (Railway)
    
# Database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'railway',
            'USER': 'root',
            'PASSWORD': 'tURpzCVocUPLKDzdHZTnHUnZTFASaVHI',
            'HOST': 'nozomi.proxy.rlwy.net',   # or the IP of your database server
            'PORT': '16562',        # default MySQL port
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# -----------------------------------
# Password Validation
# -----------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------------------
# Internationalization
# -----------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------------
# Static Files (Render Ready)
# -----------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -----------------------------------
# Default Primary Key Field Type
# -----------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------
# CORS Configuration (Allow All for now)
# -----------------------------------
CORS_ALLOW_ALL_ORIGINS = True     # ✅ Allow all for dev & first deploy
CORS_ALLOW_CREDENTIALS = True

# -----------------------------------
# Logging (optional, helpful for debugging)
# -----------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}